package com.b.kang.retrofit.database.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.b.kang.retrofit.database.entity.ZhiHuItem;

import com.b.kang.retrofit.database.dao.ZhiHuItemDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig zhiHuItemDaoConfig;

    private final ZhiHuItemDao zhiHuItemDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        zhiHuItemDaoConfig = daoConfigMap.get(ZhiHuItemDao.class).clone();
        zhiHuItemDaoConfig.initIdentityScope(type);

        zhiHuItemDao = new ZhiHuItemDao(zhiHuItemDaoConfig, this);

        registerDao(ZhiHuItem.class, zhiHuItemDao);
    }
    
    public void clear() {
        zhiHuItemDaoConfig.clearIdentityScope();
    }

    public ZhiHuItemDao getZhiHuItemDao() {
        return zhiHuItemDao;
    }

}
